# The Microsoft Store screenshots, as recipes rather than as prose.
#
# `take-shots.ps1` beside this takes a set given the recipes for it, and
# `screenshot.ps1` under that is the driver and knows nothing about Duckling.
# Both are generated by ship and the same in every repository with a window to
# photograph. This file is the part that is Duckling's - which documents, which
# frames, and what has to happen in the window before each shutter.
#
# Everything a person would change to retake the set lives at the top, and
# running it by hand on the Windows machine is the same command CI would:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1
#     ...\shots.ps1 -SideLoaded            # a build that is not packaged yet
#
# The documents go in as an array built here and handed over in this process,
# which is why there is no comma-joining rule to get wrong. `powershell -File`
# does not pass arrays - `-Documents a b c` binds `a` and then tries `b` as
# `-Width`, and the error names `Width` and an .epub path in one sentence - and
# that only ever applied to calling the driver from a command line.
#
# WHAT THE TWO SHOTS SHOW, AND WHY EACH CHOICE
#
# `packaging/submission-notes.md` carries the reasoning and this file carries the
# recipe; they are the same two frames. In short: DocLang is selected in the
# first, where the preview is not the subject, because its preview is markup
# carrying four `<location>` elements per node. Markdown is selected in the
# second, with the preview open, and it is the word people search for. The
# selected result in the first comes from a Word file, since neither a PDF nor
# the CSV reads as prose in a narrow pane. `site-survey-report.pdf` is the one
# long enough to be caught mid-conversion, and `scanned-notice.pdf` is the one
# that cannot convert without the models in the package, so a shot of it
# converted is the offline-OCR claim photographed.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

[CmdletBinding()]
param(
    # One plain capture of the queue, and nothing else. This is how the
    # coordinates below get measured: take it, open it, read the pixel of each
    # control off it, and fill the constants in.
    [switch] $Reference,
    [string] $OutDir,
    # The build under %LOCALAPPDATA% rather than the packaged one. The packaged
    # application is what a person gets and is the default; this is for looking
    # at a build that is not packaged yet.
    [switch] $SideLoaded,
    # Open the format list before the reference frame, so that the two choices
    # inside it can be measured. egui draws the list in a popup that exists
    # only while it is open, and its items take no keyboard: pressing Down and
    # Return with the list open leaves the selection where it was, so each of
    # the two shots clicks its choice and each choice needs a coordinate.
    [switch] $ListOpen,
    # Which language's set to take. `Take-Shots` turns it into `en-US` or
    # `de-DE`, the subdirectory the Store files a frame by. The queue's own
    # documents carry no translated content - only the window chrome changes -
    # so unlike flyleaf there is one set of documents and two sets of
    # coordinates: `packaging/macos/shots.sh` already measured that German
    # runs long enough to wrap Duckling's toolbar to a second row.
    [ValidateSet('en', 'de')]
    [string] $Lang = 'en'
)

$ErrorActionPreference = 'Stop'

. "$PSScriptRoot\take-shots.ps1"

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- the configuration ------------------------------------------------------

# 1366x768 is the Microsoft Store's minimum for a desktop screenshot, and a
# window this size looks like a window rather than like an advertisement.
$WIDTH = 1366
$HEIGHT = 768

# The documents the queue holds. A short readable path, because the path shows
# in the preview.
$DOCUMENTS = Join-Path $root 'packaging\demo\documents'

# The process the window belongs to, which the driver stops first so the frame
# holds this run's window and not a previous one's.
$PROCESS = 'duckling'

# Where the shots land. Not committed: dist is where every built artefact goes.
if (-not $OutDir) { $OutDir = Join-Path $root 'dist\screenshots' }

# Four steps of egui's own zoom, about 140%. The Store renders screenshots
# small, and at the default scale this application's text is around ten pixels
# - legible in the window and not in a thumbnail. It also stops the preview
# pane wrapping the DocLang into fragments. Nothing persists: eframe's
# persistence feature is off, so the next launch is back at 100%.
#
# Handed to `Take-Shots` as `-EveryShot` rather than written into each recipe,
# so that the reference frame is taken at this zoom too. Coordinates are read
# off that frame, and the zoom moves every one of them.
$ZOOM = @('key ctrl+plus', 'key ctrl+plus', 'key ctrl+plus', 'key ctrl+plus')

# The controls, by what they do rather than by where they are. Each is "X,Y" in
# the frame, at the size above and *after* the zoom, since the zoom moves
# everything. Read off a reference frame:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1 -Reference
#
# In two passes, because two of them are inside a popup and no plain frame
# shows them. The first pass gives the toolbar and the rows; fill those in,
# then take a second with `-ListOpen`, which opens the format list before the
# shutter, and read the two choices off that.
#
# German runs long enough to wrap the toolbar to a second row -
# `packaging/macos/shots.sh` measured that already - which moves every one of
# these down as well as right, so each language gets its own full set rather
# than an offset applied to the English one. Read off a reference frame and a
# `-ListOpen` frame taken on winwork: the format control stays on row one,
# shifted right; Convert drops to row two and resets to the left edge rather
# than staying under where it was; and the row list starts lower, by the
# height that second row added.
if ($Lang -eq 'de') {
    $FORMAT_CONTROL = '631,50'
    $FORMAT_DOCLANG = '640,85'
    $FORMAT_MARKDOWN = '640,115'
    $CONVERT = '66,79'
    $FIELD_NOTES_ROW = '60,230'
    $SITE_SURVEY_ROW = '60,460'
} else {
    $FORMAT_CONTROL = '436,50'    # the format control, which opens the list
    $FORMAT_DOCLANG = '440,85'    # the DocLang choice in the open list
    $FORMAT_MARKDOWN = '440,115'  # the Markdown choice in the same list
    $CONVERT = '1066,50'          # the Convert button
    # A row is selectable by its file name and not by the whole row, so these
    # are on the name. The queue is sorted by name, and these are the third
    # and tenth of the twelve.
    $FIELD_NOTES_ROW = '60,201'   # the row for field-notes.docx
    $SITE_SURVEY_ROW = '60,437'   # the row for site-survey-report.pdf
}

# A conversion is not a repaint. The first shot is caught mid-batch and the
# second waits for the batch to finish, which for a scanned PDF is the models
# loading as well as the pages.
$MID_BATCH = 3
$WHOLE_BATCH = 90

# --- how it starts ----------------------------------------------------------

# Duckling claims no file type, so there is no association to open: the
# documents are arguments. The packaged executable under `WindowsApps` cannot be
# run directly either - `Start-Process` on it fails with *Access is denied* -
# so the packaged build is reached through its apps folder moniker.
function Get-Documents {
    if (-not (Test-Path -LiteralPath $DOCUMENTS)) {
        Write-Error "shots.ps1: no documents at $DOCUMENTS"
    }
    # Files Duckling cannot read are rejected at queueing and appear as a status
    # line rather than a row, so they are dropped here: a directory is a request
    # for what can be converted, which is the rule `walk` in `src/lib.rs`
    # follows for a dropped folder.
    $readable = '.pdf', '.docx', '.pptx', '.xlsx', '.doc', '.ppt', '.xls',
                '.odt', '.odp', '.ods', '.epub', '.rtf', '.html', '.htm',
                '.md', '.markdown', '.csv'
    $inside = Get-ChildItem -LiteralPath $DOCUMENTS -File |
        Where-Object { $readable -contains $_.Extension.ToLowerInvariant() } |
        Sort-Object Name
    if (-not $inside) { Write-Error "shots.ps1: nothing Duckling reads in $DOCUMENTS" }
    return @($inside.FullName)
}

function Opens {
    $documents = Get-Documents
    if ($SideLoaded) {
        $exe = Join-Path $env:LOCALAPPDATA 'Programs\Duckling\duckling.exe'
        if (-not (Test-Path -LiteralPath $exe)) {
            Write-Error "shots.ps1: no side-loaded build at $exe - run install.ps1 first"
        }
        return @('exe', $exe) + $documents
    }
    # The identity from the one file that holds it, rather than typed here. A
    # moniker with the wrong family name starts nothing and says nothing about
    # why.
    $identityFile = Join-Path $PSScriptRoot 'identity.psd1'
    if (-not (Test-Path -LiteralPath $identityFile)) {
        Write-Error "shots.ps1: no identity at $identityFile - it is committed beside this script, or pass -SideLoaded"
    }
    $identity = Import-PowerShellDataFile $identityFile
    if (-not $identity.PackageFamilyName) { Write-Error 'shots.ps1: identity.psd1 has no PackageFamilyName' }
    if (-not (Get-AppxPackage $identity.Name -ErrorAction SilentlyContinue)) {
        Write-Error "shots.ps1: $($identity.Name) is not installed - build-msix.ps1 -SelfSign and Add-AppxPackage it, or pass -SideLoaded"
    }
    return @('package', "$($identity.PackageFamilyName)!Duckling") + $documents
}

# --- the shots --------------------------------------------------------------

# One shot to a line: name, then the actions that put the window into the state
# being photographed, in the order they are given.
#
#   click X,Y     press a control
#   double X,Y    press it twice inside the double-click interval
#   type TEXT     type
#   key NAME      one key, optionally with modifiers: ctrl+a, ctrl+plus
function Get-Shots {
    # Mid-batch: some rows still queued, the scanned PDF spinning, the rest
    # done, and a result selected from a Word file.
    Shot '01-converting' @(
        "click $FORMAT_CONTROL", "click $FORMAT_DOCLANG",
        "click $CONVERT", "click $FIELD_NOTES_ROW"
    ) -Settle $MID_BATCH

    # The batch finished, with the preview open on a PDF long enough to have
    # been worth converting, and a row showing `species-list.md` becoming
    # `species-list (1).md` - the never-overwrite rule of DESIGN.md §5 in the
    # picture.
    Shot '02-converted' @(
        "click $FORMAT_CONTROL", "click $FORMAT_MARKDOWN",
        "click $CONVERT", "click $SITE_SURVEY_ROW"
    ) -Settle $WHOLE_BATCH
}

$everyShot = $ZOOM
if ($ListOpen) {
    if (-not $Reference) { Write-Error 'shots.ps1: -ListOpen is for taking a reference frame' }
    $everyShot += "click $FORMAT_CONTROL"
}

Take-Shots -Launch (Opens) -Process $PROCESS `
    -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Lang $Lang -Reference:$Reference `
    -EveryShot $everyShot
