#!/bin/sh
# The Mac App Store screenshots, as recipes rather than as prose.
#
# `screenshot.sh` beside this is the driver and knows nothing about Duckling,
# and `take-shots.sh` beside that is the harness; both are generated by ship and
# the same in every repository with a window to photograph. This file is the
# part that is Duckling's — which document each frame opens, which frames, and
# what the desktop looks like before the shutter.
#
#     ./packaging/fetch-models.sh
#     MACOSX_DEPLOYMENT_TARGET=13.4 cargo build --release --target aarch64-apple-darwin
#     ./packaging/macos/build-app.sh
#     ./packaging/macos/shots.sh --app dist/Duckling.app --lang en
#     ./packaging/macos/shots.sh --app dist/Duckling.app --lang de
#
# WHAT THE SET SHOWS, AND WHY
#
# A conversion is under way or finished in every frame. Apple refuses a set
# under guideline 2.3.3 — *the screenshots do not show the actual app in use* —
# and Segler 0.1.0 was refused under it for four frames of a window at rest, so
# nothing here is a queue sitting still.
#
# ONE DOCUMENT TO A FRAME
#
# `screenshot.sh` takes one `--document` and launches the application afresh for
# each frame, so the queue in these pictures holds one row where the Windows set
# shows twelve. Each frame opens a different document, which makes the set a
# tour of what Duckling reads rather than four pictures of one file. The
# documents are `packaging/demo/`'s, and they are staged into the Documents
# folder first: the path is in the preview pane, so what is photographed should
# read like a person's machine rather than like a build directory.
#
# COORDINATES ARE PER LANGUAGE
#
# Every control a recipe presses is in the toolbar, and the toolbar is laid out
# by its own text: `Umwandeln in` is wider than `Convert to`, so the format
# control and the Convert button sit further right in a German window. A single
# set of coordinates would press the wrong pixel in one of the two languages, so
# each language carries its own, read off its own reference frame:
#
#     ./packaging/macos/shots.sh --app dist/Duckling.app --lang de --reference
#
# The queue row is measured too rather than shared, for the same reason the
# others are: a column header's width is the header's text.
#
# LIGHT LEADS, AND THREE OF FOUR ARE LIGHT
#
# The application follows the system appearance, a fresh macOS installation is
# light, and the product page shows the first picture largest. Dark is worth a
# slot because following the appearance is worth showing, and worth only one.
#
# THE APPEARANCE IS THE DESKTOP'S
#
# No control in the window changes it, so it is set before each launch. The
# driver stops whatever is running and launches again for every frame, so a
# value written here is read at the start it belongs to. It is read back,
# because a frame taken after an appearance that did not take is a duplicate of
# its pair, and that is the sort of thing that reaches a listing.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "${here}/../.." && pwd)

# --- the configuration ------------------------------------------------------

# App Store Connect takes 1440x900 for macOS, and every coordinate below was
# read off a frame of that size. Change it and they all move.
WIDTH=1440
HEIGHT=900

OUTDIR="${root}/dist/screenshots"

# The demo documents, which `packaging/demo/README.md` accounts for.
# `site-survey-report.pdf` is the one long enough to be caught mid-conversion,
# and `field-notes.docx` converts fast enough that a frame taken a moment later
# is of a finished one.
DOCUMENTS="${root}/packaging/demo/documents"
CONVERTING_DOC=site-survey-report.pdf
CONVERTED_DOC=field-notes.docx

# --- the appearance ---------------------------------------------------------

# Asked of System Events rather than written with `defaults`.
#
# **`defaults write -g AppleInterfaceStyle Dark` is not enough, and it reads
# back as though it were.** It writes the value and `defaults read` returns it,
# because both go through the same preferences cache; the window server is
# never told, and an application launched afterwards still draws light. The dark
# frame then comes back a pixel-for-pixel duplicate of its light pair, which is
# the failure the read-back below is there to prevent.
#
# System Events sets it the way the Settings pane does. It is already trusted
# for Accessibility on a runner, which is what the driver needs anyway.
appearance() {
    case "$1" in
        light) want=false ;;
        dark) want=true ;;
        *) echo "shots.sh: appearance is light or dark, not $1" >&2; exit 2 ;;
    esac
    osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to ${want}" >/dev/null
    sleep 1
    got=$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode')
    [ "$got" = "$want" ] || {
        echo "shots.sh: asked for $1 and the desktop reads dark mode ${got}" >&2
        exit 1
    }
    echo "shots.sh: desktop set to $1"
}

# --- where the controls are, per language -----------------------------------

# Each is "X,Y" in the frame at 1440x900, read off `00-reference.png` in that
# language's own directory. `--reference` takes it.
#
#   FORMAT_CONTROL  the format control in the toolbar, which opens the list of
#                   output formats
#   CONVERT         the Convert button
#   ROW             the queue's one row, on the file name: a row is selectable
#                   by its name and not by the whole row

en_format_control=''
en_convert=''
en_row=''

de_format_control=''
de_convert=''
de_row=''

# --- which document each frame opens, and where its controls are -------------

# Both languages open the same documents. The window is what differs — Duckling
# reads POTEXT_LANG before it asks the platform, and the driver passes the
# language through `open --env` — and the documents themselves are English in
# both sets. anderix/ship#8 carries that.
for_language() {
    case "$1" in
        en|en-US|en-us)
            FORMAT_CONTROL=$en_format_control
            CONVERT=$en_convert
            ROW=$en_row
            ;;
        de|de-DE|de-de)
            FORMAT_CONTROL=$de_format_control
            CONVERT=$de_convert
            ROW=$de_row
            ;;
        *) echo "shots.sh: no set is written for $1" >&2; exit 2 ;;
    esac

    staged="${HOME}/Documents"
    mkdir -p "$staged"
    for name in "$CONVERTING_DOC" "$CONVERTED_DOC"; do
        [ -f "${DOCUMENTS}/${name}" ] || {
            echo "shots.sh: no document at ${DOCUMENTS}/${name}" >&2
            exit 1
        }
        cp "${DOCUMENTS}/${name}" "${staged}/${name}"
    done
    converting="${staged}/${CONVERTING_DOC}"
    converted="${staged}/${CONVERTED_DOC}"

    # Duckling writes its output beside the input and never over an existing
    # file, so a rerun that found the last run's results would photograph
    # `field-notes (1).md` rather than `field-notes.md`.
    rm -f "${staged}/${CONVERTING_DOC%.*}"*.dclg "${staged}/${CONVERTED_DOC%.*}"*.dclg
    rm -f "${staged}/${CONVERTING_DOC%.*}"*.md "${staged}/${CONVERTED_DOC%.*}"*.md

    # The harness wants a document before it will run anything, and the first
    # frame's is the one it checks.
    document=$converting
}

# --- the shots --------------------------------------------------------------

# DocLang is the format the window opens on, so the two frames that convert
# press Convert and nothing else: a recipe that set the format would need the
# list's two choices measured as well, for a frame that shows the same result.
shots() {
    # A PDF part-way through: the layout model working, the status column
    # reading Converting, and the preview pane on the row it belongs to. This is
    # the frame guideline 2.3.3 asks for.
    appearance light
    document=$converting
    shot 01-light-converting --click "$CONVERT" --click "$ROW"

    # The same act finished: the preview naming the file that was written, with
    # Open and Show in folder under it.
    document=$converted
    shot 02-light-converted --click "$CONVERT" --click "$ROW"

    # The output formats, listed. The claim on the listing page is that one
    # queue converts to any of ten, and this is the only frame that shows all
    # ten at once.
    shot 03-light-the-output-formats \
        --click "$CONVERT" --click "$ROW" --click "$FORMAT_CONTROL"

    # The same conversion in the dark appearance. The only difference from 02 is
    # the desktop's, so a reader comparing them sees the application rather than
    # two different demonstrations.
    appearance dark
    shot 04-dark-converted --click "$CONVERT" --click "$ROW"
}

. "${here}/take-shots.sh"
take_shots "$@"
